apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-to-services
  namespace: ecom
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: ecom
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx