FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules node_modules
COPY tsconfig.json ./
COPY src src
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/dist dist
COPY package*.json ./
COPY --from=deps /app/node_modules node_modules
EXPOSE 8080
CMD ["node", "dist/server.js"]