apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecom
  labels: { app: cart-service }
spec:
  selector: { app: cart-service }
  ports:
  - name: http
    port: 80
    targetPort: 8080