apiVersion: v1
kind: Namespace
metadata:
  name: ecom
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: ecom
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]