# Create app namespace with restricted Pod Security
apiVersion: v1
kind: Namespace
metadata:
  name: ecom
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
# Monitoring namespace for Prometheus/Grafana (Helm handles most resources)
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring