# SecretProviderClass: syncs Key Vault secrets -> K8s Secret "app-secrets" in ecom namespace
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: ecom
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "<your-kv-name>"             # replaced in pipeline
    cloudName: ""
    tenantId: "<tenant-guid>"                  # optional if using managed identity + RBAC
    objects: |
      array:
        - |
          objectName: COSMOS_CONN_STR
          objectType: secret
        - |
          objectName: SERVICEBUS_CONN_STR
          objectType: secret
        - |
          objectName: REDIS_CONN_STR
          objectType: secret
        - |
          objectName: STRIPE_SECRET
          objectType: secret
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: COSMOS_CONN_STR
      key: COSMOS_CONN_STR
    - objectName: SERVICEBUS_CONN_STR
      key: SERVICEBUS_CONN_STR
    - objectName: REDIS_CONN_STR
      key: REDIS_CONN_STR
    - objectName: STRIPE_SECRET
      key: STRIPE_SECRET